### ISSUE TITLE
Zła wersja w stopce

### ISSUE THREAD

**Issue by Jaom** [emkael/aktywator#1]
![image](https://user-images.githubusercontent.com/2835003/27658647-09d86360-5c51-11e7-9859-a9ce92f7732b.png)

**Comment by emkael** [comment]
Poprawiłem opis stopki w aecbbb3.
Zaktualizowałem paczkę w tagu 1.0.7:
https://github.com/emkael/aktywator/releases/download/v1.0.7/Aktywator.zip
